all:

	@echo "Compiling phonebook 🛠️"
	c++ *.cpp -Wall -Wextra -Werror -std=c++98 -o phonebook
	@echo "phonebook is ready ✅"
	./phonebook
	@echo "Cleaning $(NAME) 🧹"
	@rm -rf phonebook
	@echo "phonebook is cleaned ✅"

# ---- end ---------------------------------------------------------------------

