/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_signals.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: sternero <sternero@student.42malaga.com>   #+#  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024-10-16 16:25:52 by sternero          #+#    #+#             */
/*   Updated: 2024-10-16 16:25:52 by sternero         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/minishell.h"

void	handler(int sig)
{
	if (sig == SIGINT)
	{
		rl_on_new_line();
		rl_redisplay();
		ft_putstr_fd("  ", 1);
		printf("\n");
		rl_replace_line("", 0);
		rl_on_new_line();
		rl_redisplay();
	}
	else if (sig == SIGQUIT)
	{
		rl_on_new_line();
		rl_replace_line("  ", 0);
		rl_redisplay();
	}
}

/*	handler function is used to handle the signals received. For example, if the 
	SIGINT signal (Interrupt, usually generated by Ctrl+C) is received, it will 
	clear the line and display a new prompt. If the SIGQUIT signal (Exit, usually
	generated by Ctrl+\) is received, it will clear the line and display a new 
	prompt. */

void	if_signal(void)
{
	struct sigaction sig;

	sig.sa_handler = &handler;
	sig.sa_flags = SA_RESTART; 
	sigemptyset(&sig.sa_mask); 
	sigaction(SIGINT, &sig, NULL);
	sigaction(SIGQUIT, &sig, NULL);
}

/*	if_signal function is used to check if the signal is received. For example, 
	if the user presses Ctrl + C to exit the program or Ctrl + D to terminate 
	the shell forcefully.
	- sig.sa_handler = &handler; is used to call the handler function when the 
		signal is received.
	- sig.sa_flags = SA_RESTART; is used to restart the system call if it is
		interrupted by a signal.
	- sigemptyset(&sig.sa_mask); is used to initialize the signal mask sa_mask 
		to an empty set. This means that other signals will not be blocked while
		the current signal is being handled.
	- sigaction(SIGINT, &sig, NULL); is used to change the action taken when the
		SIGINT signal (Interrupt, usually generated by Ctrl+C) is received. The 
		sig structure is passed to specify the new signal handler.
	- sigaction(SIGQUIT, &sig, NULL); is used to change the action taken when 
		the SIGQUIT signal (Exit, usually generated by Ctrl+\) is received. */
