# ---- MAKEFILE ----------------------------------------------------------------

all:

	@echo "Compiling HI THIS IS BRAIN 🛠️"
	c++ *.cpp -Wall -Wextra -Werror -std=c++98 -o brain
	@echo "HI THIS IS BRAIN is ready ✅"
	./brain
	@echo "Cleaning HI THIS IS BRAIN 🧹"
	@rm -rf brain
	@echo "HI THIS IS BRAIN is cleaned ✅"

# ---- end ---------------------------------------------------------------------
