#version: '3.8'
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    restart: always
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
    networks: 
      - inception
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sternero/data/mysql

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sternero/data/wordpress

