FROM hashicorp/vault:1.13
COPY srcs/secrets/certs/fullchain.pem /vault/certs/fullchain.pem
COPY srcs/secrets/certs/privkey.pem /vault/certs/privkey.pem
COPY srcs/data/vault/config/vault.hcl /vault/config/vault.hcl