# ***** APARIENCE ************************************************************ #

# Colors
RED = \033[0;31m
GREEN = \033[0;32m
YELLOW = \033[0;33m
BLUE = \033[0;34m
PURPLE = \033[0;35m
CYAN = \033[0;36m
WHITE = \033[0;37m

# Reset
RESET = \033[0m

# ***** VARIABLES ************************************************************ #

# Name of the executable
NAME_P = push_swap
NAME_C = checker

# ***** DIRECTORIES ********************************************************** #

# Directories
DIR_S = srcs
DIR_O = objs
DIR_I = includes
DIR_L = libft
DIR_P = ft_printf

# ***** FILES **************************************************************** #

# Source files
SRC_P = $DIR_S/push_swap.c 

