# ---- MAKEFILE ----------------------------------------------------------------

all:

	@echo "Compiling Unnecessary violence 🛠️"
	c++ *.cpp -Wall -Wextra -Werror -std=c++98 -o attack
	@echo "Unnecessary violence is ready ✅"
	@echo ""
	./attack
	@echo ""
	@echo "Cleaning Unnecessary violence 🧹"
	@rm -rf attack
	@echo "Unnecessary violence is cleaned ✅"

# ---- end ---------------------------------------------------------------------